export const DataDestinations = [
    {
      id: 1,
      country: 'Espagne',            
      locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/mallorca-1.png?updatedAt=1726395884335",
      description: 'L\'Espagne est une destination ensoleillée offrant des plages magnifiques, une cuisine exquise, et une histoire riche. Des villes emblématiques comme Barcelone, Madrid et Séville regorgent de culture et de divertissements.',
      destinations: [
        {
            id: 1,
            name: 'Hotel BQ Aguamarina Boutique',
            country: 'Espagne',
            location: 'Majorque, Espagne',
            locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/mallorca-1.png?updatedAt=1726395884335",
            stars: 4,
            price: 204,
            features: [
            'Un emplacement privilégié en bord de mer',
            'Des chambres spacieuses avec un coin salon séparé, idéales pour les familles',
            'Un hôtel moderne familial',
            ],
            image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-1.webp?updatedAt=1726408453507',
            pension: 'Tout compris',
            description: "Situé sur l'île ensoleillée de Majorque, le BQ Aguamarina Boutique offre une vue imprenable sur la mer Méditerranée. Cet hôtel charmant allie confort moderne et élégance traditionnelle pour une escapade parfaite au bord de l'eau.",
            images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-1.webp?updatedAt=1726408453507',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-5.webp?updatedAt=1726408716922',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-3.webp?updatedAt=1726408453569',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-2.webp?updatedAt=1726408453560',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-4.webp?updatedAt=1726408453563',
            "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/mallorca-1.png?updatedAt=1726395884335",
            ],
        },
        {
            id: 2,
            name: 'Hotel Santa Catalina',
            country: 'Espagne',
            location: 'Îles Canaries, Espagne',
            locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/gran-canaria-1.jpg?updatedAt=1726395884235',
            stars: 3,
            price: 150,
            features: [
            'Un accès direct à la plage',
            'Des chambres familiales avec kitchenette',
            'Un programme d’activités pour tous les âges',
            ],
            image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-2.webp?updatedAt=1726511279357',
            pension: 'Demi pension',
            description: "Perché sur les falaises emblématiques de Santorin, Astarte Suites propose un cadre romantique avec des vues à couper le souffle sur la caldeira. Profitez du luxe et de la tranquillité dans un décor paradisiaque.",
            images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-5.webp?updatedAt=1726511337836',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-3.webp?updatedAt=1726511337852',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-6.webp?updatedAt=1726511337840',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-2.webp?updatedAt=1726511279357',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-1.jpg?updatedAt=1726511337714',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-1.webp?updatedAt=1726511337788',
            ],
        },
        {
            id: 3,
            name: 'Bless Hotel',
            location: 'Ibiza, Espagne',
            country: 'Espagne',
            locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/gran-canaria-1.jpg?updatedAt=1726395884235',
            stars: 4,
            price: 265,
            features: [
              'Situé au cœur de la vie nocturne',
              'Des chambres avec vue sur la mer',
              'Un rooftop avec piscine et bar',
            ],
            image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-5.webp?updatedAt=1726409798616',
            pension: 'Tout compris',
            description: "Situé à Ibiza, le Bless Hotel propose une expérience de luxe et de style, parfait pour ceux qui cherchent à se détendre tout en profitant de la vie nocturne vibrante de l'île. Un mélange parfait entre confort et élégance.",
            images: [
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-5.webp?updatedAt=1726409798616',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-1.webp?updatedAt=1726409798598',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-3.webp?updatedAt=1726409798489',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-2.webp?updatedAt=1726409798350',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-4.webp?updatedAt=1726409798651',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/ibiza-1.jpg?updatedAt=1726395884215',
            ],
        },
      ],
    },
    {
      id: 2,
      country: 'France',
      locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/corse-1.jpg?updatedAt=1726420022963",
      description: 'La France est réputée pour son romantisme, son art, et sa gastronomie. Des paysages variés comme la Côte d\'Azur, la Provence, et les Alpes en font une destination de choix, sans oublier Paris, la ville lumière.',
      destinations: [
        {
            id: 1,
            name: 'Les Regalia Hôtel & Spa',
            country: 'France',
            location: 'Corse, France',
            locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/corse-1.jpg?updatedAt=1726420022963",
            stars: 4,
            price: 419,
            features: [
              'Un cadre naturel exceptionnel',
              'Des activités de plein air pour toute la famille',
              'Un restaurant gastronomique avec vue panoramique',
            ],
            image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-3.webp?updatedAt=1726511640941',
            pension: 'Tout compris',
            description: "Situé au cœur de la Corse, Les Regalia Hôtel & Spa vous propose une escapade raffinée avec des vues imprenables sur les montagnes et la mer. L'endroit idéal pour se ressourcer avec des services de spa de classe mondiale.",
            images: [
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-2.webp?updatedAt=1726511640926',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-3.webp?updatedAt=1726511640941',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-4.webp?updatedAt=1726511640874',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-5.webp?updatedAt=1726511640864',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-6.webp?updatedAt=1726511640901',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-1.webp?updatedAt=1726511640902',
            ],
          },
      ],
    },
    {
      id: 3,
      country: 'Grèce',
      locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/santorini-1.jpg?updatedAt=1726395884168",
      description: 'La Grèce, berceau de la civilisation occidentale, est connue pour ses îles paradisiaques telles que Santorin et Mykonos, ainsi que ses monuments historiques comme l\'Acropole à Athènes.',
      destinations: [
        {
            id: 1,
            name: 'Astarte Suites',
            country: 'Grèce',
            location: 'Santorin, Grèce',
            locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/santorini-1.jpg?updatedAt=1726395884168',
            stars: 5,
            price: 180,
            features: [
              'Une vue imprenable sur la mer Égée',
              'Des suites de luxe avec balcon privé',
              'Un spa complet et piscine à débordement',
            ],
            image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-2.jpg?updatedAt=1726410160703',
            pension: 'Tout compris',
            description: "Perché sur les falaises emblématiques de Santorin, Astarte Suites propose un cadre romantique avec des vues à couper le souffle sur la caldeira. Profitez du luxe et de la tranquillité dans un décor paradisiaque.",
            images: [
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-1.jpg?updatedAt=1726410160692',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-2.jpg?updatedAt=1726410160703',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-3.jpg?updatedAt=1726410160680',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-4.webp?updatedAt=1726410160816',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-5.webp?updatedAt=1726410160797',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/santorini-1.jpg?updatedAt=1726395884168',
            ],
          },
      ],
    },
    {
      id: 4,
      country: 'Porto Rico',
      locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/puerto-rico-1.jpg?updatedAt=1726395884231",
      description: 'Porto Rico offre un mélange unique de culture caribéenne et espagnole. Avec ses plages magnifiques, sa forêt tropicale d\'El Yunque et la vibrante ville de San Juan, c\'est une destination idéale pour se détendre et explorer.',
      destinations: [
        {
            id: 1,
            name: 'Hôtel Tres Sirenas Beach',
            country: 'Porto Rico',
            location: 'San Juan, Porto Rico',
            locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/puerto-rico-1.jpg?updatedAt=1726395884231",
            stars: 3,
            price: 120,
            features: [
              'Un resort all inclusive',
              'Des villas privées avec piscine',
              'Un accès à une plage privée',
            ],
            image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-2.jpg?updatedAt=1726410910812',
            pension: 'Petit-déjeuner ',
            description: "Placé directement sur les plages de sable doré de San Juan, l'Hôtel Tres Sirenas Beach est un véritable paradis tropical. Profitez de l'océan à vos pieds, dans un cadre chaleureux et relaxant.",
            images: [
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-1.jpg?updatedAt=1726410910774',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-2.jpg?updatedAt=1726410910812',      
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-3.jpg?updatedAt=1726410910771',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-4.jpg?updatedAt=1726410924196',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-5.jpg?updatedAt=1726410924246',
              'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/puerto-rico-1.jpg?updatedAt=1726395884231',
            ],
          },
      ],
    },
    {
      id: 5,
      country: 'Maroc',
      locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/maroc-1.jpg?updatedAt=1726582135476",
      description: 'Le Maroc est une destination riche en culture, avec des paysages variés allant des plages dorées aux montagnes impressionnantes. Les villes comme Marrakech, Fès et Casablanca offrent un mélange fascinant de traditions anciennes et de modernité.',
      destinations: [
        {
          id: 1,
          name: "Dunes d'Or Ocean Club",
          country: 'Maroc',
          location: 'Agadir, Maroc',
          locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/maroc-1.jpg?updatedAt=1726582135476',
          stars: 4,
          price: 120,
          features: [
            'Emplacement idéal près de la plage',
            'Chambres confortables avec vue sur la mer',
            'Piscine extérieure et spa',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Maroc/hotel-maroc-1.jpg?updatedAt=1726582803177',
          pension: 'Petit-déjeuner',
          description: 'Le Suite Azur Hotel à Agadir est un choix parfait pour ceux qui cherchent à combiner détente et découverte. Profitez de chambres élégantes, d’une vue magnifique sur l’océan et d’un accès facile aux plages et attractions locales.',
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Maroc/hotel-maroc-2.jpg?updatedAt=1726582803106',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Maroc/hotel-maroc-6.jpg?updatedAt=1726582802920',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Maroc/hotel-maroc-5.jpg?updatedAt=1726582802958',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Maroc/hotel-maroc-4.jpg?updatedAt=1726582802899',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Maroc/hotel-maroc-3.jpg?updatedAt=1726582802893',
           'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Maroc/hotel-maroc-1.jpg?updatedAt=1726582803177',
          ],
        },
      ],
    },
    {
      id: 6,
      country: 'Venezuela',
      locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/venezuela-1.jpg?updatedAt=1726582329478",
      description: 'Le Venezuela est un pays riche en paysages divers, allant des plages paradisiaques des Caraïbes aux vastes plaines de l’Orénoque. Connue pour sa biodiversité impressionnante, ses parcs nationaux et ses villes vibrantes, la destination idéale pour les amoureux de la nature et de la culture.',
      destinations: [
        {
          id: 1,
          name: 'Hotel Los Roques Paradise',
          country: 'Venezuela',
          location: 'Archipel de Los Roques, Venezuela',
          locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/venezuela-1.jpg?updatedAt=1726582329478',
          stars: 4,
          price: 250,
          features: [
            'Accès direct à une plage privée',
            'Chambres avec vue sur l’océan',
            'Services de plongée et de snorkeling',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-roques-1.jpg?updatedAt=1726583305478',
          pension: 'Tout compris',
          description: 'L’Hotel Los Roques Paradise est une oasis de luxe située dans l’archipel de Los Roques. Profitez d’une expérience unique avec des chambres confortables, une vue imprenable sur les plages paradisiaques et une offre complète de loisirs nautiques.',
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-roques-6.webp?updatedAt=1726583527244',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-roques-5.webp?updatedAt=1726583527302',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-roques-4.webp?updatedAt=1726583527317',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-roques-2.jpg?updatedAt=1726583305417',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-roques-3.jpg?updatedAt=1726583305612',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-roques-1.jpg?updatedAt=1726583305478',
          ],
        },
        {
          id: 1,
          name: 'Hotel Margarita Tropical',
          country: 'Venezuela',
          location: 'Île Margarita, Venezuela',
          locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/ile-margarita-1.jpg?updatedAt=1726582456789',
          stars: 4,
          price: 180,
          features: [
            'Plage privée',
            'Piscine extérieure',
            'Activités nautiques',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-margarita-1.webp?updatedAt=1726584125962',
          pension: 'Tout compris',
          description: 'L’Hotel Margarita Tropical offre une expérience luxueuse sur l’île Margarita. Profitez d’une plage privée, d’une piscine rafraîchissante et d’une gamme d’activités nautiques pour toute la famille. Un choix parfait pour une escapade tropicale.',
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-margarita-4.webp?updatedAt=1726584125862',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-margarita-2.webp?updatedAt=1726584125851',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-margarita-5.webp?updatedAt=1726584125913',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-margarita-3.webp?updatedAt=1726584125910',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-margarita-6.webp?updatedAt=1726584038771',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Venezuela/hotel-margarita-1.webp?updatedAt=1726584125962'
          ],
        },
      ],
    },
  ];
  