export const Data = [
        {
          id: 1,
          name: 'Hotel BQ Aguamarina Boutique',
          country: 'Espagne',
          location: 'Majorque, Espagne',
          locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/mallorca-1.png?updatedAt=1726395884335",
          stars: 4,
          price: 204,
          features: [
            'Un emplacement privilégié en bord de mer',
            'Des chambres spacieuses avec un coin salon séparé, idéales pour les familles',
            'Un hôtel moderne familial',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-1.webp?updatedAt=1726408453507',
          pension: 'Tout compris',
          description: "Situé sur l'île ensoleillée de Majorque, le BQ Aguamarina Boutique offre une vue imprenable sur la mer Méditerranée. Cet hôtel charmant allie confort moderne et élégance traditionnelle pour une escapade parfaite au bord de l'eau.",
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-1.webp?updatedAt=1726408453507',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-5.webp?updatedAt=1726408716922',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-3.webp?updatedAt=1726408453569',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-2.webp?updatedAt=1726408453560',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Majorque/hotel-majorque-4.webp?updatedAt=1726408453563',
            "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/mallorca-1.png?updatedAt=1726395884335",
          ],
        },
        {
          id: 2,
          name: 'Astarte Suites',
          country: 'Grèce',
          location: 'Santorin, Grèce',
          locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/santorini-1.jpg?updatedAt=1726395884168',
          stars: 5,
          price: 180,
          features: [
            'Une vue imprenable sur la mer Égée',
            'Des suites de luxe avec balcon privé',
            'Un spa complet et piscine à débordement',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-2.jpg?updatedAt=1726410160703',
          pension: 'Tout compris',
          description: "Perché sur les falaises emblématiques de Santorin, Astarte Suites propose un cadre romantique avec des vues à couper le souffle sur la caldeira. Profitez du luxe et de la tranquillité dans un décor paradisiaque.",
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-1.jpg?updatedAt=1726410160692',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-2.jpg?updatedAt=1726410160703',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-3.jpg?updatedAt=1726410160680',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-4.webp?updatedAt=1726410160816',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Santorini/hotel-santorini-5.webp?updatedAt=1726410160797',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/santorini-1.jpg?updatedAt=1726395884168',
          ],
        },
        {
          id: 3,
          name: 'Hotel Santa Catalina,',
          country: 'Espagne',
          location: 'Îles Canaries, Espagne',
          locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/gran-canaria-1.jpg?updatedAt=1726395884235',
          stars: 3,
          price: 150,
          features: [
            'Un accès direct à la plage',
            'Des chambres familiales avec kitchenette',
            'Un programme d’activités pour tous les âges',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-2.webp?updatedAt=1726511279357',
          pension: 'Demi pension',
          description: "Perché sur les falaises emblématiques de Santorin, Astarte Suites propose un cadre romantique avec des vues à couper le souffle sur la caldeira. Profitez du luxe et de la tranquillité dans un décor paradisiaque.",
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-5.webp?updatedAt=1726511337836',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-3.webp?updatedAt=1726511337852',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-6.webp?updatedAt=1726511337840',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-2.webp?updatedAt=1726511279357',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-1.jpg?updatedAt=1726511337714',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Canaries/hotel-canaries-1.webp?updatedAt=1726511337788',
          ],
        },
        {
          id: 4,
          name: 'Bless Hotel',
          location: 'Ibiza, Espagne',
          country: 'Espagne',
          locationImage: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/gran-canaria-1.jpg?updatedAt=1726395884235',
          stars: 4,
          price: 265,
          features: [
            'Situé au cœur de la vie nocturne',
            'Des chambres avec vue sur la mer',
            'Un rooftop avec piscine et bar',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-5.webp?updatedAt=1726409798616',
          pension: 'Tout compris',
          description: "Situé à Ibiza, le Bless Hotel propose une expérience de luxe et de style, parfait pour ceux qui cherchent à se détendre tout en profitant de la vie nocturne vibrante de l'île. Un mélange parfait entre confort et élégance.",
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-5.webp?updatedAt=1726409798616',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-1.webp?updatedAt=1726409798598',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-3.webp?updatedAt=1726409798489',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-2.webp?updatedAt=1726409798350',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Ibiza/hotel-ibiza-4.webp?updatedAt=1726409798651',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/ibiza-1.jpg?updatedAt=1726395884215',
          ],
        },
        {
          id: 5,
          name: 'Hôtel Tres Sirenas Beach',
          country: 'Porto Rico',
          location: 'San Juan, Porto Rico',
          locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/puerto-rico-1.jpg?updatedAt=1726395884231",
          stars: 3,
          price: 120,
          features: [
            'Un resort all inclusive',
            'Des villas privées avec piscine',
            'Un accès à une plage privée',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-2.jpg?updatedAt=1726410910812',
          pension: 'Petit-déjeuner ',
          description: "Placé directement sur les plages de sable doré de San Juan, l'Hôtel Tres Sirenas Beach est un véritable paradis tropical. Profitez de l'océan à vos pieds, dans un cadre chaleureux et relaxant.",
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-1.jpg?updatedAt=1726410910774',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-2.jpg?updatedAt=1726410910812',      
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-3.jpg?updatedAt=1726410910771',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-4.jpg?updatedAt=1726410924196',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Puerto%20Rico/hotel-puerto-5.jpg?updatedAt=1726410924246',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/puerto-rico-1.jpg?updatedAt=1726395884231',
          ],
        },
        {
          id: 6,
          name: 'Les Regalia Hôtel & Spa',
          country: 'France',
          location: 'Corse, France',
          locationImage: "https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/corse-1.jpg?updatedAt=1726420022963",
          stars: 4,
          price: 419,
          features: [
            'Un cadre naturel exceptionnel',
            'Des activités de plein air pour toute la famille',
            'Un restaurant gastronomique avec vue panoramique',
          ],
          image: 'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-3.webp?updatedAt=1726511640941',
          pension: 'Tout compris',
          description: "Situé au cœur de la Corse, Les Regalia Hôtel & Spa vous propose une escapade raffinée avec des vues imprenables sur les montagnes et la mer. L'endroit idéal pour se ressourcer avec des services de spa de classe mondiale.",
          images: [
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-2.webp?updatedAt=1726511640926',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-3.webp?updatedAt=1726511640941',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-4.webp?updatedAt=1726511640874',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-5.webp?updatedAt=1726511640864',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-6.webp?updatedAt=1726511640901',
            'https://ik.imagekit.io/logoMGM/Derni%C3%A8reMinute/Corse/hotel-corse-1.webp?updatedAt=1726511640902',
          ],
        },
      ];